In [18]:
# pip install pydot

In [19]:
# pip install graphviz

In [20]:
# pip install --upgrade tensorflow

In [21]:
import tensorflow as tf
print(tf.__version__)

2.18.0

In [22]:
import seaborn as sns
import pandas as pd
import numpy as np

from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.optimizers import Adam

In [23]:
## import dataset
iris_data=sns.load_dataset('iris')
iris_data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [24]:
attr=iris_data.drop(['species'],axis=1)
target=pd.get_dummies(iris_data.species,prefix='ouput')
print(attr.shape)
print(target.shape)
attr.head()
target.head()

(150, 4)
(150, 3)

   ouput_setosa  ouput_versicolor  ouput_virginica
0          True             False            False
1          True             False            False
2          True             False            False
3          True             False            False
4          True             False            False

In [25]:
attr.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [26]:
## convert the data frames to arrays
X=attr.values
y=target.values
print(type(X))
print(type(y))
print(X.shape)
print(y.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(150, 4)
(150, 3)

In [27]:
 #creating test and training
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=.20,random_state=100)
x_train, x_test, y_train, y_test=train_test_split(X,y,test_size=.20,random_state=100)
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(120, 4)
(120, 3)
(30, 4)
(30, 3)

In [28]:
print(x_train.shape)
print(y_train.shape)

(120, 4)
(120, 3)

In [ ]:

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam

dropout_rate = 0.1
epochs = 50
batch_size = 1
learn_rate = 0.001

model = Sequential()
model.add(Input(shape=(x_train.shape[1],)))
model.add(Dense(12, activation='relu'))
model.add(Dropout(dropout_rate))
model.add(Dense(6, activation='sigmoid'))
model.add(Dropout(dropout_rate))
model.add(Dense(y_train.shape[1], activation='softmax'))

adam = Adam(learning_rate=learn_rate)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

#Dropout 
#Purpose: Dropout is a regularization technique used to prevent overfitting in neural networks.
#How it works: 
#During training, dropout randomly sets a fraction of the neurons (defined by the dropout_rate) to zero in each forward pass.
#his forces the network to learn more robust features by not relying too heavily on specific neurons.

In [30]:
## you nee graphviz for ploting
from tensorflow.keras.utils import plot_model
# run in colab for graphviz plot
plot_model(model,to_file='model_plot1.png',show_shapes=True, show_layer_names=True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [37]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 12)             │            60 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 12)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 6)              │            78 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 479 (1.88 KB)

 Trainable params: 159 (636.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 320 (1.25 KB)

In [32]:
model_history = model.fit(x_train,y_train, batch_size=batch_size,epochs=epochs,validation_split=.2,verbose=1)

Epoch 1/50

96/96 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.3232 - loss: 1.4471 - val_accuracy: 0.2917 - val_loss: 1.4664
Epoch 2/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4432 - loss: 1.1384 - val_accuracy: 0.4167 - val_loss: 1.2985
Epoch 3/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4769 - loss: 1.2252 - val_accuracy: 0.5000 - val_loss: 1.1682
Epoch 4/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5453 - loss: 1.0818 - val_accuracy: 0.5000 - val_loss: 1.0599
Epoch 5/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6795 - loss: 0.9018 - val_accuracy: 0.5000 - val_loss: 0.9707
Epoch 6/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6501 - loss: 0.8867 - val_accuracy: 0.5000 - val_loss: 0.8965
Epoch 7/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6582 - loss: 0.7509 - val_accuracy: 0.5000 - val_loss: 0.8326
Epoch 8/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6445 - loss: 0.7734 - val_accuracy: 0.6250 - val_loss: 0.7712
Epoch 9/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7120 - loss: 0.6795 - val_accuracy: 0.7500 - val_loss: 0.7231
Epoch 10/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7407 - loss: 0.6455 - val_accuracy: 0.8333 - val_loss: 0.6819
Epoch 11/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7162 - loss: 0.6718 - val_accuracy: 0.8333 - val_loss: 0.6464
Epoch 12/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7071 - loss: 0.6772 - val_accuracy: 0.8333 - val_loss: 0.6213
Epoch 13/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8204 - loss: 0.5427 - val_accuracy: 0.8333 - val_loss: 0.5940
Epoch 14/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7706 - loss: 0.6454 - val_accuracy: 0.8333 - val_loss: 0.5680
Epoch 15/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7814 - loss: 0.5842 - val_accuracy: 0.8750 - val_loss: 0.5471
Epoch 16/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8399 - loss: 0.5075 - val_accuracy: 0.8750 - val_loss: 0.5271
Epoch 17/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7447 - loss: 0.5770 - val_accuracy: 0.8750 - val_loss: 0.5050
Epoch 18/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9369 - loss: 0.4329 - val_accuracy: 0.8750 - val_loss: 0.4851
Epoch 19/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8042 - loss: 0.5027 - val_accuracy: 0.9167 - val_loss: 0.4656
Epoch 20/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8464 - loss: 0.4579 - val_accuracy: 0.9583 - val_loss: 0.4490
Epoch 21/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7523 - loss: 0.5716 - val_accuracy: 0.9583 - val_loss: 0.4333
Epoch 22/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8925 - loss: 0.4630 - val_accuracy: 0.9583 - val_loss: 0.4175
Epoch 23/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8160 - loss: 0.4664 - val_accuracy: 0.9583 - val_loss: 0.4028
Epoch 24/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8472 - loss: 0.4532 - val_accuracy: 0.9583 - val_loss: 0.3900
Epoch 25/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8433 - loss: 0.4199 - val_accuracy: 0.9583 - val_loss: 0.3754
Epoch 26/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9002 - loss: 0.3847 - val_accuracy: 0.9583 - val_loss: 0.3596
Epoch 27/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9146 - loss: 0.3914 - val_accuracy: 0.9583 - val_loss: 0.3475
Epoch 28/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8930 - loss: 0.3726 - val_accuracy: 1.0000 - val_loss: 0.3338
Epoch 29/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8957 - loss: 0.3378 - val_accuracy: 1.0000 - val_loss: 0.3204
Epoch 30/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8598 - loss: 0.4197 - val_accuracy: 1.0000 - val_loss: 0.3089
Epoch 31/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9089 - loss: 0.3434 - val_accuracy: 1.0000 - val_loss: 0.2946
Epoch 32/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8689 - loss: 0.3748 - val_accuracy: 1.0000 - val_loss: 0.2818
Epoch 33/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9215 - loss: 0.3101 - val_accuracy: 1.0000 - val_loss: 0.2700
Epoch 34/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8033 - loss: 0.3767 - val_accuracy: 1.0000 - val_loss: 0.2589
Epoch 35/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9484 - loss: 0.3037 - val_accuracy: 1.0000 - val_loss: 0.2479
Epoch 36/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9110 - loss: 0.3141 - val_accuracy: 1.0000 - val_loss: 0.2404
Epoch 37/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9044 - loss: 0.3190 - val_accuracy: 1.0000 - val_loss: 0.2317
Epoch 38/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9258 - loss: 0.2581 - val_accuracy: 1.0000 - val_loss: 0.2219
Epoch 39/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8708 - loss: 0.3189 - val_accuracy: 1.0000 - val_loss: 0.2157
Epoch 40/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9279 - loss: 0.3094 - val_accuracy: 1.0000 - val_loss: 0.2058
Epoch 41/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9005 - loss: 0.3110 - val_accuracy: 1.0000 - val_loss: 0.1965
Epoch 42/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9323 - loss: 0.2774 - val_accuracy: 1.0000 - val_loss: 0.1886
Epoch 43/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8775 - loss: 0.3147 - val_accuracy: 1.0000 - val_loss: 0.1836
Epoch 44/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8514 - loss: 0.3496 - val_accuracy: 1.0000 - val_loss: 0.1762
Epoch 45/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9482 - loss: 0.2584 - val_accuracy: 1.0000 - val_loss: 0.1695
Epoch 46/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8996 - loss: 0.2812 - val_accuracy: 1.0000 - val_loss: 0.1628
Epoch 47/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9643 - loss: 0.1886 - val_accuracy: 1.0000 - val_loss: 0.1570
Epoch 48/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9651 - loss: 0.1920 - val_accuracy: 1.0000 - val_loss: 0.1478
Epoch 49/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9308 - loss: 0.2797 - val_accuracy: 1.0000 - val_loss: 0.1426
Epoch 50/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9323 - loss: 0.2346 - val_accuracy: 1.0000 - val_loss: 0.1387

In [33]:
accuracies = model.evaluate(x_test, y_test, verbose=1)
print("Test score:", accuracies[0])
print("Test Accuracy;", accuracies[1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 223ms/step - accuracy: 1.0000 - loss: 0.1586
Test score: 0.1585613191127777
Test Accuracy; 1.0

In [34]:
# print(accuracies)