In [9]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import jaccard_score

In [10]:
data = pd.read_csv('D:\Stevens GIT\Stevens_IT-MS_in_CS\SPRING_25\CS513_Knowledge_Discovery&Data_Mining\Classwork\Disease.csv', index_col='Symptoms ')
data = data.T
data.head(20)

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\abdul\AppData\Local\Temp\ipykernel_21424\4036616685.py:1: SyntaxWarning: invalid escape sequence '\S'
  data = pd.read_csv('D:\Stevens GIT\Stevens_IT-MS_in_CS\SPRING_25\CS513_Knowledge_Discovery&Data_Mining\Classwork\Disease.csv', index_col='Symptoms ')

Symptoms,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7
Disease_1,1,1,0,1,1,1,1
Disease_2,1,1,1,0,1,0,1
Disease_3,1,1,1,1,1,0,1
Disease_4,1,1,1,1,1,0,1
Disease_5,1,1,1,1,0,0,1
Disease_6,1,1,1,1,0,0,0
Disease_7,0,1,0,1,0,0,0
Disease_8,0,0,0,1,0,1,0
Disease_9,0,1,0,1,0,0,0
Disease_10,0,0,0,0,0,1,0
New_Patient,0,0,1,0,0,1,0

In [11]:
cos_sim = pd.DataFrame(cosine_similarity(data.T))
cos_sim.columns = data.columns
cos_sim['Symptoms'] = [e for e in data.columns]
cos_sim = cos_sim.set_index(['Symptoms'])
cos_sim

Symptoms,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7
Symptoms,,,,,,,
Symptom_1,1.000000,0.866025,0.833333,0.721688,0.816497,0.204124,0.912871
Symptom_2,0.866025,1.000000,0.721688,0.875000,0.707107,0.176777,0.790569
Symptom_3,0.833333,0.721688,1.000000,0.577350,0.612372,0.204124,0.730297
Symptom_4,0.721688,0.875000,0.577350,1.000000,0.530330,0.353553,0.632456
Symptom_5,0.816497,0.707107,0.612372,0.530330,1.000000,0.250000,0.894427
Symptom_6,0.204124,0.176777,0.204124,0.353553,0.250000,1.000000,0.223607
Symptom_7,0.912871,0.790569,0.730297,0.632456,0.894427,0.223607,1.000000

In [12]:
jac_sim = pd.DataFrame(columns = [e for e in data.columns])
jac_sim['index'] = [e for e in data.columns]
jac_sim = jac_sim.set_index(['index'])
for ind in [e for e in data.columns]:
    for col in [e for e in data.columns]:
        jac_sim.loc[ind,col] = jaccard_score(data[ind],data[col])
jac_sim

,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7
index,,,,,,,
Symptom_1,1.0,0.75,0.714286,0.555556,0.666667,0.111111,0.833333
Symptom_2,0.75,1.0,0.555556,0.777778,0.5,0.090909,0.625
Symptom_3,0.714286,0.555556,1.0,0.4,0.428571,0.111111,0.571429
Symptom_4,0.555556,0.777778,0.4,1.0,0.333333,0.2,0.444444
Symptom_5,0.666667,0.5,0.428571,0.333333,1.0,0.142857,0.8
Symptom_6,0.111111,0.090909,0.111111,0.2,0.142857,1.0,0.125
Symptom_7,0.833333,0.625,0.571429,0.444444,0.8,0.125,1.0