In [2]:
import pandas as pd

In [3]:
rating_df=pd.read_csv('C:/Users/kdehn/OneDrive - stevens.edu/___Data/CSV_files/Movie_utility_1.csv',index_col='User')
for col in rating_df.select_dtypes(include=['int', 'float']).columns:
    rating_df[col] = rating_df[col].astype(float)



rating_df.head()

      Movie_1  Movie_2  Movie_3  Movie_4  Movie_5  Movie_6  Movie_7  Movie_8
User
A         4.0      0.0      0.0      5.0      1.0      0.0      0.0      3.0
B         5.0      5.0      4.0      0.0      0.0      0.0      0.0      5.0
C         0.0      0.0      0.0      2.0      4.0      5.0      0.0      1.0
D         0.0      3.0      0.0      0.0      0.0      0.0      3.0      0.0
E         5.0      5.0      0.0      0.0      0.0      0.0      5.0      0.0

In [4]:

row_mean=rating_df.mean(numeric_only=True, axis=1) 
print(row_mean)
row_mean_lst=list(row_mean)
print(row_mean_lst)

User
A    1.625
B    2.375
C    1.500
D    0.750
E    1.875
E    1.375
dtype: float64
[1.625, 2.375, 1.5, 0.75, 1.875, 1.375]

In [5]:
df_centered= rating_df.copy()
for i in range(0,len(row_mean_lst)):
    for j in range(0,len(rating_df.columns)):
        if (rating_df.iloc[i,j])> 0:
            adjust=rating_df.iloc[i,j]-row_mean_lst[i]
            # print(adjust)
            df_centered.iloc[i,j]=adjust
df_centered.head()

      Movie_1  Movie_2  Movie_3  Movie_4  Movie_5  Movie_6  Movie_7  Movie_8
User
A       2.375    0.000    0.000    3.375   -0.625      0.0    0.000    1.375
B       2.625    2.625    1.625    0.000    0.000      0.0    0.000    2.625
C       0.000    0.000    0.000    0.500    2.500      3.5    0.000   -0.500
D       0.000    2.250    0.000    0.000    0.000      0.0    2.250    0.000
E       3.125    3.125    0.000    0.000    0.000      0.0    3.125    0.000

In [6]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim = pd.DataFrame(cosine_similarity(df_centered))
cos_sim.columns = df_centered.T.columns
cos_sim['User'] = [c for c in df_centered.T.columns]
cos_sim=cos_sim.set_index(['User'])
cos_sim.head()

User         A         B         C         D         E         E
User
A     1.000000  0.463924 -0.029365  0.000000  0.312021  0.541603
B     0.463924  1.000000 -0.062363  0.384432  0.627775  0.237348
C    -0.029365 -0.062363  1.000000  0.000000  0.000000  0.080895
D     0.000000  0.384432  0.000000  1.000000  0.816497 -0.051586
E     0.312021  0.627775  0.000000  0.816497  1.000000 -0.042120

In [7]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim = pd.DataFrame(cosine_similarity(df_centered.T))
cos_sim.columns = df_centered.columns
cos_sim['Movie'] = [c for c in df_centered.columns]
cos_sim=cos_sim.set_index(['Movie'])
cos_sim.head(7)

,Movie_1,Movie_2,Movie_3,Movie_4,Movie_5,Movie_6,Movie_7,Movie_8
Movie,,,,,,,,
Movie_1,1.000000,0.756899,0.227400,0.341000,-0.121988,0.000000,0.534546,0.715711
Movie_2,0.756899,1.000000,0.230406,0.000000,0.000000,0.000000,0.822387,0.492002
Movie_3,0.227400,0.230406,1.000000,0.664483,0.000000,0.000000,-0.088446,0.357304
Movie_4,0.341000,0.000000,0.664483,1.000000,-0.066991,0.100440,-0.070581,0.293488
Movie_5,-0.121988,0.000000,0.000000,-0.066991,1.000000,0.970143,0.000000,-0.272380
Movie_6,0.000000,0.000000,0.000000,0.100440,0.970143,1.000000,0.000000,-0.166378
Movie_7,0.534546,0.822387,-0.088446,-0.070581,0.000000,0.000000,1.000000,0.000000