In [1]:
from numpy import dot
from numpy.linalg import norm
# List1 = [1,1]
# List2 = [1,0]
# arr=[[1,1],
#      [1,0]
#     ]
List1 = [0.666667,0.000000,0.000000,1.666667,-2.333333,0.000000,0.0]
List2 = [0.333333,0.333333,-0.666667,0.000000,0.000000,0.000000, 0.0]
arr=[ 
    [0.666667,0.000000,0.000000,1.666667,-2.333333,0.000000,0.0],
     [0.333333,0.333333,-0.666667,0.000000,0.000000,0.000000, 0.0] 
    ]
print(arr)
result = dot(List1, List2)/(norm(List1)*norm(List2))
print(result)
from sklearn.metrics.pairwise import cosine_similarity
cos_sim=cosine_similarity(arr)
print(cos_sim)

[[0.666667, 0.0, 0.0, 1.666667, -2.333333, 0.0, 0.0], [0.333333, 0.333333, -0.666667, 0.0, 0.0, 0.0, 0.0]]
0.09244998647911737
[[1.         0.09244999]
 [0.09244999 1.        ]]

In [3]:
import pandas as pd
from sklearn.metrics import jaccard_score
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
data = pd.read_csv('C:/Users/kdehn/OneDrive - stevens.edu/___Data/CSV_files/movie_actor.csv', index_col='Movie')
data = data.T
data.head()

Movie   Movie1  Movie2  Movie3  Movie4  Movie5  Movie6  Movie7
Actor1       1       0       0       0       1       1       0
Actor2       1       1       1       0       0       0       1
Actor3       0       0       1       1       0       0       0
Actor4       1       0       1       0       0       0       0
Actor5       0       0       0       1       0       0       1

In [9]:
jac_sim = pd.DataFrame(columns = [e for e in data.columns])
jac_sim['index'] = [e for e in data.columns]
jac_sim = jac_sim.set_index(['index'])
for ind in [e for e in data.columns]:
    for col in [e for e in data.columns]:
        jac_sim.loc[ind,col] = jaccard_score(data[ind],data[col])
jac_sim

       Movie1    Movie2    Movie3    Movie4    Movie5    Movie6    Movie7
index
Movie1    1.0      0.25       0.5       0.0      0.25       0.2      0.25
Movie2   0.25       1.0      0.25       0.2       0.0       0.0  0.333333
Movie3    0.5      0.25       1.0  0.166667       0.0       0.0      0.25
Movie4    0.0       0.2  0.166667       1.0       0.0  0.166667       0.2
Movie5   0.25       0.0       0.0       0.0       1.0  0.666667       0.0
Movie6    0.2       0.0       0.0  0.166667  0.666667       1.0       0.0
Movie7   0.25  0.333333      0.25       0.2       0.0       0.0       1.0

In [10]:
cos_sim = pd.DataFrame(cosine_similarity(data.T))
cos_sim.columns = data.columns
cos_sim['Recipe'] = [e for e in data.columns]
cos_sim = cos_sim.set_index(['Recipe'])
cos_sim

Movie     Movie1    Movie2    Movie3    Movie4    Movie5    Movie6    Movie7
Recipe
Movie1  1.000000  0.408248  0.666667  0.000000  0.408248  0.333333  0.408248
Movie2  0.408248  1.000000  0.408248  0.353553  0.000000  0.000000  0.500000
Movie3  0.666667  0.408248  1.000000  0.288675  0.000000  0.000000  0.408248
Movie4  0.000000  0.353553  0.288675  1.000000  0.000000  0.288675  0.353553
Movie5  0.408248  0.000000  0.000000  0.000000  1.000000  0.816497  0.000000
Movie6  0.333333  0.000000  0.000000  0.288675  0.816497  1.000000  0.000000
Movie7  0.408248  0.500000  0.408248  0.353553  0.000000  0.000000  1.000000