In [2]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import jaccard_score

In [6]:
data = pd.read_csv('C:/Users/kdehn/OneDrive - stevens.edu/___Data/CSV_files/Disease.csv', index_col='Symptoms ')
# data = data.T
data.head(20)

,Disease_1,Disease_2,Disease_3,Disease_4,Disease_5,Disease_6,Disease_7,Disease_8,Disease_9,Disease_10,New_Patient
Symptoms,,,,,,,,,,,
Symptom_1,1,1,1,1,1,1,0,0,0,0,0
Symptom_2,1,1,1,1,1,1,1,0,1,0,0
Symptom_3,0,1,1,1,1,1,0,0,0,0,1
Symptom_4,1,0,1,1,1,1,1,1,1,0,0
Symptom_5,1,1,1,1,0,0,0,0,0,0,0
Symptom_6,1,0,0,0,0,0,0,1,0,1,1
Symptom_7,1,1,1,1,1,0,0,0,0,0,0

In [7]:
cos_sim = pd.DataFrame(cosine_similarity(data.T))
cos_sim.columns = data.columns
cos_sim['Symptoms'] = [e for e in data.columns]
cos_sim = cos_sim.set_index(['Symptoms'])
cos_sim

,Disease_1,Disease_2,Disease_3,Disease_4,Disease_5,Disease_6,Disease_7,Disease_8,Disease_9,Disease_10,New_Patient
Symptoms,,,,,,,,,,,
Disease_1,1.000000,0.730297,0.833333,0.833333,0.730297,0.612372,0.577350,0.577350,0.577350,0.408248,0.288675
Disease_2,0.730297,1.000000,0.912871,0.912871,0.800000,0.670820,0.316228,0.000000,0.316228,0.000000,0.316228
Disease_3,0.833333,0.912871,1.000000,1.000000,0.912871,0.816497,0.577350,0.288675,0.577350,0.000000,0.288675
Disease_4,0.833333,0.912871,1.000000,1.000000,0.912871,0.816497,0.577350,0.288675,0.577350,0.000000,0.288675
Disease_5,0.730297,0.800000,0.912871,0.912871,1.000000,0.894427,0.632456,0.316228,0.632456,0.000000,0.316228
Disease_6,0.612372,0.670820,0.816497,0.816497,0.894427,1.000000,0.707107,0.353553,0.707107,0.000000,0.353553
Disease_7,0.577350,0.316228,0.577350,0.577350,0.632456,0.707107,1.000000,0.500000,1.000000,0.000000,0.000000
Disease_8,0.577350,0.000000,0.288675,0.288675,0.316228,0.353553,0.500000,1.000000,0.500000,0.707107,0.500000
Disease_9,0.577350,0.316228,0.577350,0.577350,0.632456,0.707107,1.000000,0.500000,1.000000,0.000000,0.000000
Disease_10,0.408248,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.707107,0.000000,1.000000,0.707107
New_Patient,0.288675,0.316228,0.288675,0.288675,0.316228,0.353553,0.000000,0.500000,0.000000,0.707107,1.000000

In [8]:
jac_sim = pd.DataFrame(columns = [e for e in data.columns])
jac_sim['index'] = [e for e in data.columns]
jac_sim = jac_sim.set_index(['index'])
for ind in [e for e in data.columns]:
    for col in [e for e in data.columns]:
        jac_sim.loc[ind,col] = jaccard_score(data[ind],data[col])
jac_sim

,Disease_1,Disease_2,Disease_3,Disease_4,Disease_5,Disease_6,Disease_7,Disease_8,Disease_9,Disease_10,New_Patient
index,,,,,,,,,,,
Disease_1,1.0,0.571429,0.714286,0.714286,0.571429,0.428571,0.333333,0.333333,0.333333,0.166667,0.142857
Disease_2,0.571429,1.0,0.833333,0.833333,0.666667,0.5,0.166667,0.0,0.166667,0.0,0.166667
Disease_3,0.714286,0.833333,1.0,1.0,0.833333,0.666667,0.333333,0.142857,0.333333,0.0,0.142857
Disease_4,0.714286,0.833333,1.0,1.0,0.833333,0.666667,0.333333,0.142857,0.333333,0.0,0.142857
Disease_5,0.571429,0.666667,0.833333,0.833333,1.0,0.8,0.4,0.166667,0.4,0.0,0.166667
Disease_6,0.428571,0.5,0.666667,0.666667,0.8,1.0,0.5,0.2,0.5,0.0,0.2
Disease_7,0.333333,0.166667,0.333333,0.333333,0.4,0.5,1.0,0.333333,1.0,0.0,0.0
Disease_8,0.333333,0.0,0.142857,0.142857,0.166667,0.2,0.333333,1.0,0.333333,0.5,0.333333
Disease_9,0.333333,0.166667,0.333333,0.333333,0.4,0.5,1.0,0.333333,1.0,0.0,0.0
Disease_10,0.166667,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,1.0,0.5
New_Patient,0.142857,0.166667,0.142857,0.142857,0.166667,0.2,0.0,0.333333,0.0,0.5,1.0